
stages:
  - containers
  - builds
  - sanity_checks

.native_git_build_job:
  extends:
    - .gitlab_native_build_job
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - export SCRATCH_DIR="/tmp/scratch"
    - export VROOT="$SCRATCH_DIR/vroot"
    - export LIBDIR="$VROOT/lib"
    - export LD_LIBRARY_PATH="$LIBDIR"
    - export PATH="$VROOT/bin:$PATH"
    - export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - popd
    - ant build jar docs
    - if test "$TESTS" != "skip" ; then ant test ; fi
    - ant src
    - if test -x /usr/bin/rpmbuild ; then ant spec && rpmbuild -ba --define "_sourcedir `pwd`/target" target/libvirt-java.spec ; fi

.native_build_job:
  extends:
    - .gitlab_native_build_job
  script:
    - ant build jar docs
    - if test "$TESTS" != "skip" ; then ant test ; fi
    - ant src
    - if test -x /usr/bin/rpmbuild ; then ant spec && rpmbuild -ba --define "_sourcedir `pwd`/target" target/libvirt-java.spec ; fi

.website:
  script:
    - ant docs
    - cp -rf site public
    - mv target/javadoc public/
  artifacts:
    paths:
      - public

pages:
  extends:
    - .website
    - .gitlab_native_build_job
  needs:
    - job: x86_64-ubuntu-2204-container
      optional: true
  variables:
    NAME: ubuntu-2204

include: '/ci/gitlab.yml'
