/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libvirt_VirDomain_CreateFlags */

#ifndef _Included_org_libvirt_VirDomain_CreateFlags
#define _Included_org_libvirt_VirDomain_CreateFlags
#ifdef __cplusplus
extern "C" {
#endif
#undef org_libvirt_VirDomain_CreateFlags_VIR_DOMAIN_NONE
#define org_libvirt_VirDomain_CreateFlags_VIR_DOMAIN_NONE 0L
#ifdef __cplusplus
}
#endif
#endif
