/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libvirt_VirDomain_MigrateFlags */

#ifndef _Included_org_libvirt_VirDomain_MigrateFlags
#define _Included_org_libvirt_VirDomain_MigrateFlags
#ifdef __cplusplus
extern "C" {
#endif
#undef org_libvirt_VirDomain_MigrateFlags_VIR_MIGRATE_LIVE
#define org_libvirt_VirDomain_MigrateFlags_VIR_MIGRATE_LIVE 1L
#ifdef __cplusplus
}
#endif
#endif
